import React, { useState, useEffect } from 'react';
import {
  Bell,
  AlertTriangle,
  ShieldAlert,
  Droplets,
  TrafficCone,
  CheckCircle2,
  Filter,
  Check,
  Eye,
  Clock,
  MapPin,
  Bus
} from 'lucide-react';
import { api } from '../services/api';
import { useSimulation } from '../context/SimulationContext';
import { useAuth } from '../context/AuthContext';
import { Alert } from '../types';

export const Alerts: React.FC = () => {
  const { user } = useAuth();
  const { activeAlertsCount } = useSimulation();

  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [ackFilter, setAckFilter] = useState('UNACKNOWLEDGED');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAlerts();
  }, [severityFilter, ackFilter]);

  const loadAlerts = () => {
    const isAck = ackFilter === 'ALL' ? undefined : ackFilter === 'ACKNOWLEDGED';
    const sev = severityFilter === 'ALL' ? undefined : severityFilter;

    api.getAlerts(sev, isAck).then((data) => {
      setAlerts(data);
      setLoading(false);
    }).catch(() => setLoading(false));
  };

  const handleAcknowledge = async (alertId: string) => {
    await api.acknowledgeAlert(alertId, user?.full_name || 'Administrator');
    loadAlerts();
  };

  const handleResolve = async (alertId: string) => {
    await api.resolveAlert(alertId);
    loadAlerts();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2.5">
            <Bell className="w-5 h-5 text-rose-500" />
            <span>Smart City Emergency & Safety Alerts Center</span>
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Priority dispatch alerts generated by Edge AI units across road defects, accidents, and traffic anomalies
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-3">
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          <select
            value={ackFilter}
            onChange={(e) => setAckFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="UNACKNOWLEDGED">Pending Action</option>
            <option value="ACKNOWLEDGED">Acknowledged</option>
            <option value="ALL">All Alerts</option>
          </select>
        </div>
      </div>

      {/* Alert Cards List */}
      <div className="space-y-3">
        {alerts.length > 0 ? (
          alerts.map((alert) => (
            <div
              key={alert.id}
              className={`p-4 rounded-xl border transition-all flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-xl ${
                alert.severity === 'CRITICAL'
                  ? 'bg-rose-950/20 border-rose-500/40 hover:border-rose-500'
                  : alert.severity === 'HIGH'
                  ? 'bg-amber-950/20 border-amber-500/40 hover:border-amber-500'
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              {/* Alert Content */}
              <div className="flex items-start gap-3.5 min-w-0">
                <div
                  className={`p-2.5 rounded-xl shrink-0 mt-0.5 ${
                    alert.severity === 'CRITICAL'
                      ? 'bg-rose-500/20 text-rose-400'
                      : alert.severity === 'HIGH'
                      ? 'bg-amber-500/20 text-amber-400'
                      : 'bg-cyan-500/20 text-cyan-400'
                  }`}
                >
                  {alert.alert_type.includes('HIT_AND_RUN') || alert.alert_type.includes('RASH') ? (
                    <ShieldAlert className="w-5 h-5" />
                  ) : alert.alert_type.includes('WATERLOGGING') ? (
                    <Droplets className="w-5 h-5" />
                  ) : alert.alert_type.includes('CONGESTION') ? (
                    <TrafficCone className="w-5 h-5" />
                  ) : (
                    <AlertTriangle className="w-5 h-5" />
                  )}
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs font-bold text-cyan-400">{alert.alert_code}</span>
                    <span className="text-sm font-bold text-white tracking-tight">{alert.title}</span>
                    <span
                      className={`px-2 py-0.2 rounded text-[10px] font-bold ${
                        alert.severity === 'CRITICAL'
                          ? 'bg-rose-500/25 text-rose-300 border border-rose-500/40 animate-pulse'
                          : alert.severity === 'HIGH'
                          ? 'bg-amber-500/25 text-amber-300 border border-amber-500/40'
                          : 'bg-slate-800 text-slate-300 border border-slate-700'
                      }`}
                    >
                      {alert.severity}
                    </span>
                  </div>

                  <p className="text-xs text-slate-300 mt-1">{alert.message}</p>

                  <div className="flex items-center gap-4 mt-2 text-[11px] text-slate-400 flex-wrap">
                    {alert.bus_id && (
                      <span className="flex items-center gap-1 font-mono text-slate-300">
                        <Bus className="w-3.5 h-3.5 text-cyan-400" />
                        {alert.bus_id}
                      </span>
                    )}
                    <span className="flex items-center gap-1 text-slate-400 font-mono">
                      <Clock className="w-3.5 h-3.5" />
                      {new Date(alert.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                    {alert.is_acknowledged && (
                      <span className="text-emerald-400 flex items-center gap-1 font-medium">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        Acknowledged by {alert.acknowledged_by}
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                {!alert.is_acknowledged && (
                  <button
                    onClick={() => handleAcknowledge(alert.id)}
                    className="px-3 py-1.5 rounded-lg bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
                  >
                    <Check className="w-3.5 h-3.5" />
                    <span>Acknowledge</span>
                  </button>
                )}

                <button
                  onClick={() => handleResolve(alert.id)}
                  className="px-3 py-1.5 rounded-lg bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border border-emerald-500/40 text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5"
                >
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Mark Resolved</span>
                </button>
              </div>
            </div>
          ))
        ) : (
          <div className="p-12 text-center bg-slate-900 border border-slate-800 rounded-xl text-slate-400 text-xs">
            No alerts matching the selected filters.
          </div>
        )}
      </div>
    </div>
  );
};
