import React, { useState, useEffect } from 'react';
import {
  Bell,
  AlertTriangle,
  ShieldAlert,
  Droplets,
  TrafficCone,
  CheckCircle2,
  Filter,
  Check,
  Eye,
  Clock,
  MapPin,
  Bus
} from 'lucide-react';
import { api } from '../services/api';
import { useSimulation } from '../context/SimulationContext';
import { useAuth } from '../context/AuthContext';
import { Alert } from '../types';

export const Alerts: React.FC = () => {
  const { user } = useAuth();
  const { activeAlertsCount } = useSimulation();

  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [ackFilter, setAckFilter] = useState('UNACKNOWLEDGED');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAlerts();
  }, [severityFilter, ackFilter]);

  const loadAlerts = () => {
    const isAck = ackFilter === 'ALL' ? undefined : ackFilter === 'ACKNOWLEDGED';
    const sev = severityFilter === 'ALL' ? undefined : severityFilter;

    api.getAlerts(sev, isAck).then((data) => {
      setAlerts(data);
      setLoading(false);
    }).catch(() => setLoading(false));
  };

  const handleAcknowledge = async (alertId: string) => {
    await api.acknowledgeAlert(alertId, user?.full_name || 'Administrator');
    loadAlerts();
  };

  const handleResolve = async (alertId: string) => {
    await api.resolveAlert(alertId);
    loadAlerts();
  };

  return (
    <div className="space-y-6 text-slate-800 dark:text-slate-100 font-sans">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div>
          <h1 className="text-2xl font-heading font-extrabold text-[#063269] dark:text-white tracking-tight flex items-center gap-2.5">
            <Bell className="w-6 h-6 text-rose-600 dark:text-rose-400" />
            <span>Smart City Emergency & Safety Alerts Center</span>
          </h1>
          <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">
            Priority dispatch alerts generated by Edge AI units across road defects, accidents, and traffic anomalies
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-3">
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 text-xs text-slate-700 dark:text-slate-200 focus:outline-none focus:border-[#0284c7] shadow-2xs font-medium cursor-pointer"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          <select
            value={ackFilter}
            onChange={(e) => setAckFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 text-xs text-slate-700 dark:text-slate-200 focus:outline-none focus:border-[#0284c7] shadow-2xs font-medium cursor-pointer"
          >
            <option value="UNACKNOWLEDGED">Pending Action</option>
            <option value="ACKNOWLEDGED">Acknowledged</option>
            <option value="ALL">All Alerts</option>
          </select>
        </div>
      </div>

      {/* Alert Cards List */}
      <div className="space-y-3">
        {alerts.length > 0 ? (
          alerts.map((alert) => (
            <div
              key={alert.id}
              className={`p-4 rounded-xl border transition-all flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-sm bg-white dark:bg-[#111c2e] hover:border-slate-300 dark:hover:border-slate-700 ${
                alert.severity === 'CRITICAL'
                  ? 'border-l-4 border-l-rose-500 border-slate-200 dark:border-slate-800'
                  : alert.severity === 'HIGH'
                  ? 'border-l-4 border-l-amber-500 border-slate-200 dark:border-slate-800'
                  : 'border-l-4 border-l-[#0284c7] border-slate-200 dark:border-slate-800'
              }`}
            >
              {/* Alert Content */}
              <div className="flex items-start gap-3.5 min-w-0">
                <div
                  className={`p-2.5 rounded-xl shrink-0 mt-0.5 ${
                    alert.severity === 'CRITICAL'
                      ? 'bg-rose-50 dark:bg-rose-950/50 text-rose-600 dark:text-rose-400 border border-rose-200 dark:border-rose-900/60'
                      : alert.severity === 'HIGH'
                      ? 'bg-amber-50 dark:bg-amber-950/50 text-amber-600 dark:text-amber-400 border border-amber-200 dark:border-amber-900/60'
                      : 'bg-sky-50 dark:bg-sky-950/50 text-[#0284c7] dark:text-sky-400 border border-sky-200 dark:border-sky-900/60'
                  }`}
                >
                  {alert.alert_type.includes('HIT_AND_RUN') || alert.alert_type.includes('RASH') ? (
                    <ShieldAlert className="w-5 h-5" />
                  ) : alert.alert_type.includes('WATERLOGGING') ? (
                    <Droplets className="w-5 h-5" />
                  ) : alert.alert_type.includes('CONGESTION') ? (
                    <TrafficCone className="w-5 h-5" />
                  ) : (
                    <AlertTriangle className="w-5 h-5" />
                  )}
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs font-bold text-[#0284c7] dark:text-sky-400">{alert.alert_code}</span>
                    <span className="text-sm font-bold text-slate-900 dark:text-white tracking-tight">{alert.title}</span>
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        alert.severity === 'CRITICAL'
                          ? 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800'
                          : alert.severity === 'HIGH'
                          ? 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-800'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'
                      }`}
                    >
                      {alert.severity}
                    </span>
                  </div>

                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1">{alert.message}</p>

                  <div className="flex items-center gap-4 mt-2 text-[11px] text-slate-500 dark:text-slate-400 flex-wrap">
                    {alert.bus_id && (
                      <span className="flex items-center gap-1 font-mono text-slate-700 dark:text-slate-300 font-semibold">
                        <Bus className="w-3.5 h-3.5 text-[#0284c7] dark:text-sky-400" />
                        {alert.bus_id}
                      </span>
                    )}
                    <span className="flex items-center gap-1 text-slate-500 dark:text-slate-400 font-mono">
                      <Clock className="w-3.5 h-3.5" />
                      {new Date(alert.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                    {alert.is_acknowledged && (
                      <span className="text-emerald-700 dark:text-emerald-400 flex items-center gap-1 font-semibold">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        Acknowledged by {alert.acknowledged_by}
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                {!alert.is_acknowledged && (
                  <button
                    onClick={() => handleAcknowledge(alert.id)}
                    className="px-3.5 py-1.5 rounded-lg bg-amber-50 dark:bg-amber-950/60 hover:bg-amber-100 dark:hover:bg-amber-900/80 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-800 text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5 shadow-2xs"
                  >
                    <Check className="w-3.5 h-3.5" />
                    <span>Acknowledge</span>
                  </button>
                )}

                <button
                  onClick={() => handleResolve(alert.id)}
                  className="px-3.5 py-1.5 rounded-lg bg-emerald-50 dark:bg-emerald-950/60 hover:bg-emerald-100 dark:hover:bg-emerald-900/80 text-emerald-800 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800 text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5 shadow-2xs"
                >
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Mark Resolved</span>
                </button>
              </div>
            </div>
          ))
        ) : (
          <div className="p-12 text-center bg-white dark:bg-[#111c2e] border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 text-xs shadow-sm">
            No alerts matching the selected filters.
          </div>
        )}
      </div>
    </div>
  );
};
